[package]
name = "ekapkgs-update"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-stream = "0.3"
camino = "1.1"
chrono = { workspace = true }
clap = { version = "4.5.53", features = ["derive", "color"] }
directories = "5.0"
futures = "0.3"
num_cpus = "1.16"
openssl = { version = "0.10.75", features = ["vendored"] }
regex = "1.0"
reqwest = { version = "0.12", features = ["json"] }
rlimit = "0.11"
rnix = "0.12.0"
semver = "1.0"
serde = { workspace = true }
serde_json = { workspace = true }
shellexpand = "3.1"
sqlx = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
thiserror = "1.0"
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
uuid = { workspace = true }
walkdir = "2.5"

[lints]
workspace = true
